#ifndef DMA_HW_REGS_H
#define DMA_HW_REGS_H

#include <stdint.h>

#define DMA_CONTRACT_VERSION 2u

#define DMA_CSR_CTRL 0x00000000u
#define DMA_CSR_STATUS 0x00000004u
#define DMA_CSR_CACHE_CTRL 0x00000040u
#define DMA_CSR_LOOPBACK_MODE 0x00000048u
#define DMA_CSR_RING_DOORBELL 0x0000004Cu
#define DMA_CSR_RING_BASE 0x00000050u
#define DMA_CSR_RING_HW_HEAD 0x00000054u
#define DMA_CSR_RING_SW_TAIL 0x00000058u
#define DMA_CSR_RING_SIZE 0x0000005Cu
#define DMA_CSR_IRQ_ENABLE 0x00000060u
#define DMA_CSR_IRQ_STATUS 0x00000064u
#define DMA_CSR_IRQ_ACK 0x00000068u
#define DMA_CSR_IRQ_COALESCE_COUNT 0x0000006Cu
#define DMA_CSR_IRQ_COALESCE_TIMEOUT 0x00000070u
#define DMA_CSR_DEBUG_STATUS 0x000000D4u
#define DMA_CSR_DEBUG_SOURCE_PROGRESS 0x000000D8u
#define DMA_CSR_DEBUG_SINK_PROGRESS 0x000000DCu
#define DMA_CSR_DEBUG_PLAINTEXT_WORD0 0x000000E0u
#define DMA_CSR_DEBUG_PLAINTEXT_WORD1 0x000000E4u
#define DMA_CSR_DEBUG_PLAINTEXT_WORD2 0x000000E8u
#define DMA_CSR_DEBUG_PLAINTEXT_WORD3 0x000000ECu
#define DMA_CSR_DEBUG_KEY_WORD0 0x000000F0u
#define DMA_CSR_DEBUG_KEY_WORD1 0x000000F4u
#define DMA_CSR_DEBUG_KEY_WORD2 0x000000F8u
#define DMA_CSR_DEBUG_KEY_WORD3 0x000000FCu
#define DMA_CSR_COUNTER_CTRL 0x00000100u
#define DMA_CSR_ROLLBACK_EVENT_COUNT_LO 0x00000104u
#define DMA_CSR_ROLLBACK_EVENT_COUNT_HI 0x00000108u
#define DMA_CSR_RECOVERY_ACTIVE_CYCLES_LO 0x0000010Cu
#define DMA_CSR_RECOVERY_ACTIVE_CYCLES_HI 0x00000110u
#define DMA_CSR_RECOVERY_LAST_WINDOW_CYCLES_LO 0x00000114u
#define DMA_CSR_RECOVERY_LAST_WINDOW_CYCLES_HI 0x00000118u
#define DMA_CSR_RECOVERY_MAX_WINDOW_CYCLES_LO 0x0000011Cu
#define DMA_CSR_RECOVERY_MAX_WINDOW_CYCLES_HI 0x00000120u
#define DMA_CSR_ERROR_QUALIFIED_PACKET_COUNT_LO 0x00000124u
#define DMA_CSR_ERROR_QUALIFIED_PACKET_COUNT_HI 0x00000128u
#define DMA_CSR_BACKEND_TOTAL_CYCLES_LO 0x0000012Cu
#define DMA_CSR_BACKEND_TOTAL_CYCLES_HI 0x00000130u
#define DMA_CSR_BACKEND_ACCEPT_CYCLES_LO 0x00000134u
#define DMA_CSR_BACKEND_ACCEPT_CYCLES_HI 0x00000138u
#define DMA_CSR_BACKEND_STARVATION_CYCLES_LO 0x0000013Cu
#define DMA_CSR_BACKEND_STARVATION_CYCLES_HI 0x00000140u
#define DMA_CSR_HIGH_WATER_COUNT_LO 0x00000144u
#define DMA_CSR_HIGH_WATER_COUNT_HI 0x00000148u
#define DMA_CSR_DROP_PULSE_COUNT_LO 0x0000014Cu
#define DMA_CSR_DROP_PULSE_COUNT_HI 0x00000150u
#define DMA_CSR_RING_DOORBELL_KICK 0x00000001u

#define DMA_CTRL_BIT_START 0u
#define DMA_CTRL_START (1u << DMA_CTRL_BIT_START)
#define DMA_CTRL_BIT_HW_INIT 1u
#define DMA_CTRL_HW_INIT (1u << DMA_CTRL_BIT_HW_INIT)
#define DMA_CTRL_BIT_ALGO_SM4 2u
#define DMA_CTRL_ALGO_SM4 (1u << DMA_CTRL_BIT_ALGO_SM4)
#define DMA_CTRL_BIT_ENCRYPT 3u
#define DMA_CTRL_ENCRYPT (1u << DMA_CTRL_BIT_ENCRYPT)
#define DMA_CTRL_BIT_S2MM_EN 4u
#define DMA_CTRL_S2MM_EN (1u << DMA_CTRL_BIT_S2MM_EN)
#define DMA_CTRL_BIT_MM2S_EN 5u
#define DMA_CTRL_MM2S_EN (1u << DMA_CTRL_BIT_MM2S_EN)
#define DMA_CTRL_BIT_AUTH_EN 6u
#define DMA_CTRL_AUTH_EN (1u << DMA_CTRL_BIT_AUTH_EN)
#define DMA_CTRL_BIT_ACL_EN 7u
#define DMA_CTRL_ACL_EN (1u << DMA_CTRL_BIT_ACL_EN)
#define DMA_CTRL_BIT_DNA_LOCK_EN 8u
#define DMA_CTRL_DNA_LOCK_EN (1u << DMA_CTRL_BIT_DNA_LOCK_EN)
#define DMA_CTRL_BIT_SOFT_RESET 10u
#define DMA_CTRL_SOFT_RESET (1u << DMA_CTRL_BIT_SOFT_RESET)

#define DMA_COUNTER_CTRL_BIT_CLEAR_ALL 0u
#define DMA_COUNTER_CTRL_CLEAR_ALL (1u << DMA_COUNTER_CTRL_BIT_CLEAR_ALL)
#define DMA_COUNTER_CTRL_BIT_SNAPSHOT 1u
#define DMA_COUNTER_CTRL_SNAPSHOT (1u << DMA_COUNTER_CTRL_BIT_SNAPSHOT)

#define DMA_DESC_SIZE_BYTES 32u
#define DMA_DESC_WORD_BYTES 4u

#define DMA_DESC_DST_ADDR_BYTE_OFFSET 0x00000000u
#define DMA_DESC_SRC_ADDR_BYTE_OFFSET 0x00000004u
#define DMA_DESC_CTRL_LEN_ALGO_BYTE_OFFSET 0x00000008u
#define DMA_DESC_RESERVED0_BYTE_OFFSET 0x0000000Cu
#define DMA_DESC_CSW_BYTE_OFFSET 0x00000010u
#define DMA_DESC_ACTUAL_LEN_BYTE_OFFSET 0x00000014u
#define DMA_DESC_RESERVED2_BYTE_OFFSET 0x00000018u
#define DMA_DESC_RESERVED3_BYTE_OFFSET 0x0000001Cu

#define DMA_DESC_CTRL_BIT_STREAM_TLAST 30u
#define DMA_DESC_CTRL_STREAM_TLAST (1u << DMA_DESC_CTRL_BIT_STREAM_TLAST)
#define DMA_DESC_CTRL_BIT_ALGO 31u
#define DMA_DESC_CTRL_ALGO (1u << DMA_DESC_CTRL_BIT_ALGO)
#define DMA_DESC_CTRL_MASK_LEN 0x00FFFFFFu

#define DMA_DESC_CSW_BIT_OWNER 31u
#define DMA_DESC_CSW_OWNER (1u << DMA_DESC_CSW_BIT_OWNER)
#define DMA_DESC_CSW_BIT_DONE 30u
#define DMA_DESC_CSW_DONE (1u << DMA_DESC_CSW_BIT_DONE)
#define DMA_DESC_CSW_BIT_ERR 29u
#define DMA_DESC_CSW_ERR (1u << DMA_DESC_CSW_BIT_ERR)
#define DMA_DESC_CSW_MASK_STS 0x00000003u
#define DMA_DESC_CSW_STS_MASK DMA_DESC_CSW_MASK_STS
#define DMA_DESC_CSW_STS_OK 0x00000000u
#define DMA_DESC_CSW_STS_AXI_RESP 0x00000001u
#define DMA_DESC_CSW_STS_OVERFLOW_OR_MISSING_TLAST 0x00000002u
#define DMA_DESC_CSW_STS_INTERNAL 0x00000003u

#define DMA_CACHELINE_BYTES 32u
#define DMA_ALIGNMENT_BYTES 32u
#define DMA_RAW_COPY_LEN_MULTIPLE 32u

#define DMA_RAW_COPY_FIFO_DEPTH 32u
#define DMA_RAW_COPY_FIFO_MEMORY "BRAM"
#define DMA_RAW_COPY_TLAST_WIDTH 1u

#define DMA_RAW_COPY_REQUIRED_AXIS_SIGNAL_COUNT 4u
#define DMA_RAW_COPY_REQUIRED_AXIS_SIGNAL_0 "TDATA"
#define DMA_RAW_COPY_REQUIRED_AXIS_SIGNAL_1 "TVALID"
#define DMA_RAW_COPY_REQUIRED_AXIS_SIGNAL_2 "TREADY"
#define DMA_RAW_COPY_REQUIRED_AXIS_SIGNAL_3 "TLAST"

#define DMA_SUBMISSION_STEP_COUNT 5u
#define DMA_SUBMISSION_STEP_0 "flush_desc_and_src"
#define DMA_SUBMISSION_STEP_1 "dsb"
#define DMA_SUBMISSION_STEP_2 "write_sw_tail"
#define DMA_SUBMISSION_STEP_3 "dsb"
#define DMA_SUBMISSION_STEP_4 "write_doorbell"

#define DMA_VALIDATION_STEP_COUNT 4u
#define DMA_VALIDATION_STEP_0 "poll_csw_success"
#define DMA_VALIDATION_STEP_1 "invalidate_dst"
#define DMA_VALIDATION_STEP_2 "dsb"
#define DMA_VALIDATION_STEP_3 "memcmp"

#define DMA_SOFT_RESET_CLEAR_COUNT 2u
#define DMA_SOFT_RESET_CLEAR_0 "dma_state_machine"
#define DMA_SOFT_RESET_CLEAR_1 "axis_fifo"

#define DMA_SOFT_RESET_RETRY_REQUIREMENT_COUNT 3u
#define DMA_SOFT_RESET_RETRY_REQUIREMENT_0 "fifo_empty"
#define DMA_SOFT_RESET_RETRY_REQUIREMENT_1 "s2mm_no_pending_beat"
#define DMA_SOFT_RESET_RETRY_REQUIREMENT_2 "fresh_csw_observation"

#define DMA_IRQ_ENABLE_BIT_DONE 0u
#define DMA_IRQ_ENABLE_DONE (1u << DMA_IRQ_ENABLE_BIT_DONE)
#define DMA_IRQ_STATUS_BIT_DONE_PENDING 0u
#define DMA_IRQ_STATUS_DONE_PENDING (1u << DMA_IRQ_STATUS_BIT_DONE_PENDING)
#define DMA_IRQ_ACK_BIT_DONE_ACK 0u
#define DMA_IRQ_ACK_DONE_ACK (1u << DMA_IRQ_ACK_BIT_DONE_ACK)

#define DMA_IRQ_DEFAULT_COALESCE_COUNT 8u
#define DMA_IRQ_DEFAULT_COALESCE_TIMEOUT_CYCLES 5000u

#define DMA_IRQ_COMPLETION_EVENT_REQUIREMENT_COUNT 3u
#define DMA_IRQ_COMPLETION_EVENT_REQUIREMENT_0 "payload_wb_b_handshake_complete"
#define DMA_IRQ_COMPLETION_EVENT_REQUIREMENT_1 "actual_len_wb_b_handshake_complete"
#define DMA_IRQ_COMPLETION_EVENT_REQUIREMENT_2 "csw_wb_b_handshake_complete"

typedef struct __attribute__((aligned(DMA_ALIGNMENT_BYTES))) dma_desc_s {
    uint32_t dst_addr;
    uint32_t src_addr;
    uint32_t ctrl_len_algo;
    uint32_t reserved0;
    uint32_t csw;
    uint32_t actual_len;
    uint32_t reserved2;
    uint32_t reserved3;
} dma_desc_t;

#endif
