domain_path: D:\FPGAhanjia\Hetero_SoC_2026\dma_hw_platform\export\dma_hw_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
