`timescale 1ns / 1ps

module dma_raw_copy_board_wrapper #(
    parameter integer ADDR_WIDTH = 32,
    parameter integer DATA_WIDTH = 32
)(
    input  wire                    clk,
    input  wire                    rst_n,
    output wire                    dma_irq,

    input  wire [ADDR_WIDTH-1:0]   s_axil_awaddr,
    input  wire                    s_axil_awvalid,
    output wire                    s_axil_awready,
    input  wire [DATA_WIDTH-1:0]   s_axil_wdata,
    input  wire [3:0]              s_axil_wstrb,
    input  wire                    s_axil_wvalid,
    output wire                    s_axil_wready,
    output wire [1:0]              s_axil_bresp,
    output wire                    s_axil_bvalid,
    input  wire                    s_axil_bready,
    input  wire [ADDR_WIDTH-1:0]   s_axil_araddr,
    input  wire                    s_axil_arvalid,
    output wire                    s_axil_arready,
    output wire [DATA_WIDTH-1:0]   s_axil_rdata,
    output wire [1:0]              s_axil_rresp,
    output wire                    s_axil_rvalid,
    input  wire                    s_axil_rready,

    output wire [ADDR_WIDTH-1:0]   m_axi_dma_wr_awaddr,
    output wire [7:0]              m_axi_dma_wr_awlen,
    output wire [2:0]              m_axi_dma_wr_awsize,
    output wire [1:0]              m_axi_dma_wr_awburst,
    output wire [3:0]              m_axi_dma_wr_awcache,
    output wire [2:0]              m_axi_dma_wr_awprot,
    output wire                    m_axi_dma_wr_awvalid,
    input  wire                    m_axi_dma_wr_awready,
    output wire [DATA_WIDTH-1:0]   m_axi_dma_wr_wdata,
    output wire [DATA_WIDTH/8-1:0] m_axi_dma_wr_wstrb,
    output wire                    m_axi_dma_wr_wlast,
    output wire                    m_axi_dma_wr_wvalid,
    input  wire                    m_axi_dma_wr_wready,
    input  wire [1:0]              m_axi_dma_wr_bresp,
    input  wire                    m_axi_dma_wr_bvalid,
    output wire                    m_axi_dma_wr_bready,

    output wire [ADDR_WIDTH-1:0]   m_axi_s2mm_awaddr,
    output wire [7:0]              m_axi_s2mm_awlen,
    output wire [2:0]              m_axi_s2mm_awsize,
    output wire [1:0]              m_axi_s2mm_awburst,
    output wire [3:0]              m_axi_s2mm_awcache,
    output wire [2:0]              m_axi_s2mm_awprot,
    output wire                    m_axi_s2mm_awvalid,
    input  wire                    m_axi_s2mm_awready,
    output wire [DATA_WIDTH-1:0]   m_axi_s2mm_wdata,
    output wire [DATA_WIDTH/8-1:0] m_axi_s2mm_wstrb,
    output wire                    m_axi_s2mm_wlast,
    output wire                    m_axi_s2mm_wvalid,
    input  wire                    m_axi_s2mm_wready,
    input  wire [1:0]              m_axi_s2mm_bresp,
    input  wire                    m_axi_s2mm_bvalid,
    output wire                    m_axi_s2mm_bready,
    output wire [ADDR_WIDTH-1:0]   m_axi_s2mm_araddr,
    output wire [7:0]              m_axi_s2mm_arlen,
    output wire [2:0]              m_axi_s2mm_arsize,
    output wire [1:0]              m_axi_s2mm_arburst,
    output wire                    m_axi_s2mm_arvalid,
    input  wire                    m_axi_s2mm_arready,
    input  wire [DATA_WIDTH-1:0]   m_axi_s2mm_rdata,
    input  wire [1:0]              m_axi_s2mm_rresp,
    input  wire                    m_axi_s2mm_rlast,
    input  wire                    m_axi_s2mm_rvalid,
    output wire                    m_axi_s2mm_rready,

    output wire [ADDR_WIDTH-1:0]   m_axi_fetcher_araddr,
    output wire [7:0]              m_axi_fetcher_arlen,
    output wire [2:0]              m_axi_fetcher_arsize,
    output wire [1:0]              m_axi_fetcher_arburst,
    output wire                    m_axi_fetcher_arvalid,
    input  wire                    m_axi_fetcher_arready,
    input  wire [DATA_WIDTH-1:0]   m_axi_fetcher_rdata,
    input  wire [1:0]              m_axi_fetcher_rresp,
    input  wire                    m_axi_fetcher_rlast,
    input  wire                    m_axi_fetcher_rvalid,
    output wire                    m_axi_fetcher_rready
);

    dma_raw_copy_subsystem #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH)
    ) i_raw_copy (
        .clk(clk),
        .rst_n(rst_n),
        .s_axil_awaddr(s_axil_awaddr),
        .s_axil_awvalid(s_axil_awvalid),
        .s_axil_awready(s_axil_awready),
        .s_axil_wdata(s_axil_wdata),
        .s_axil_wstrb(s_axil_wstrb),
        .s_axil_wvalid(s_axil_wvalid),
        .s_axil_wready(s_axil_wready),
        .s_axil_bresp(s_axil_bresp),
        .s_axil_bvalid(s_axil_bvalid),
        .s_axil_bready(s_axil_bready),
        .s_axil_araddr(s_axil_araddr),
        .s_axil_arvalid(s_axil_arvalid),
        .s_axil_arready(s_axil_arready),
        .s_axil_rdata(s_axil_rdata),
        .s_axil_rresp(s_axil_rresp),
        .s_axil_rvalid(s_axil_rvalid),
        .s_axil_rready(s_axil_rready),
        .s_axis_tdata({DATA_WIDTH{1'b0}}),
        .s_axis_tvalid(1'b0),
        .s_axis_tready(),
        .s_axis_tlast(1'b0),

        .m_axi_awaddr(m_axi_s2mm_awaddr),
        .m_axi_awlen(m_axi_s2mm_awlen),
        .m_axi_awsize(m_axi_s2mm_awsize),
        .m_axi_awburst(m_axi_s2mm_awburst),
        .m_axi_awcache(m_axi_s2mm_awcache),
        .m_axi_awprot(m_axi_s2mm_awprot),
        .m_axi_awvalid(m_axi_s2mm_awvalid),
        .m_axi_awready(m_axi_s2mm_awready),
        .m_axi_wdata(m_axi_s2mm_wdata),
        .m_axi_wstrb(m_axi_s2mm_wstrb),
        .m_axi_wlast(m_axi_s2mm_wlast),
        .m_axi_wvalid(m_axi_s2mm_wvalid),
        .m_axi_wready(m_axi_s2mm_wready),
        .m_axi_bresp(m_axi_s2mm_bresp),
        .m_axi_bvalid(m_axi_s2mm_bvalid),
        .m_axi_bready(m_axi_s2mm_bready),

        .m_axi_araddr(m_axi_s2mm_araddr),
        .m_axi_arlen(m_axi_s2mm_arlen),
        .m_axi_arsize(m_axi_s2mm_arsize),
        .m_axi_arburst(m_axi_s2mm_arburst),
        .m_axi_arvalid(m_axi_s2mm_arvalid),
        .m_axi_arready(m_axi_s2mm_arready),
        .m_axi_rdata(m_axi_s2mm_rdata),
        .m_axi_rresp(m_axi_s2mm_rresp),
        .m_axi_rlast(m_axi_s2mm_rlast),
        .m_axi_rvalid(m_axi_s2mm_rvalid),
        .m_axi_rready(m_axi_s2mm_rready),

        .m_axi_fetcher_araddr(m_axi_fetcher_araddr),
        .m_axi_fetcher_arlen(m_axi_fetcher_arlen),
        .m_axi_fetcher_arsize(m_axi_fetcher_arsize),
        .m_axi_fetcher_arburst(m_axi_fetcher_arburst),
        .m_axi_fetcher_arvalid(m_axi_fetcher_arvalid),
        .m_axi_fetcher_arready(m_axi_fetcher_arready),
        .m_axi_fetcher_rdata(m_axi_fetcher_rdata),
        .m_axi_fetcher_rresp(m_axi_fetcher_rresp),
        .m_axi_fetcher_rlast(m_axi_fetcher_rlast),
        .m_axi_fetcher_rvalid(m_axi_fetcher_rvalid),
        .m_axi_fetcher_rready(m_axi_fetcher_rready),

        .m_axi_wb_awaddr(m_axi_dma_wr_awaddr),
        .m_axi_wb_awlen(m_axi_dma_wr_awlen),
        .m_axi_wb_awsize(m_axi_dma_wr_awsize),
        .m_axi_wb_awburst(m_axi_dma_wr_awburst),
        .m_axi_wb_awcache(m_axi_dma_wr_awcache),
        .m_axi_wb_awprot(m_axi_dma_wr_awprot),
        .m_axi_wb_awvalid(m_axi_dma_wr_awvalid),
        .m_axi_wb_awready(m_axi_dma_wr_awready),
        .m_axi_wb_wdata(m_axi_dma_wr_wdata),
        .m_axi_wb_wstrb(m_axi_dma_wr_wstrb),
        .m_axi_wb_wlast(m_axi_dma_wr_wlast),
        .m_axi_wb_wvalid(m_axi_dma_wr_wvalid),
        .m_axi_wb_wready(m_axi_dma_wr_wready),
        .m_axi_wb_bresp(m_axi_dma_wr_bresp),
        .m_axi_wb_bvalid(m_axi_dma_wr_bvalid),
        .m_axi_wb_bready(m_axi_dma_wr_bready),

        .dma_irq(dma_irq)
    );

endmodule
